#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="begin_smt")]
	public partial class SMTAssemblyLineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmaster_station(master_station instance);
    partial void Updatemaster_station(master_station instance);
    partial void Deletemaster_station(master_station instance);
    partial void Inserttrn_station(trn_station instance);
    partial void Updatetrn_station(trn_station instance);
    partial void Deletetrn_station(trn_station instance);
    #endregion
		
		public SMTAssemblyLineDataContext() : 
				base(global::ClassLibrary1.Properties.Settings.Default.begin_smtConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SMTAssemblyLineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMTAssemblyLineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMTAssemblyLineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMTAssemblyLineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<master_station> master_stations
		{
			get
			{
				return this.GetTable<master_station>();
			}
		}
		
		public System.Data.Linq.Table<trn_station> trn_stations
		{
			get
			{
				return this.GetTable<trn_station>();
			}
		}
		
		public System.Data.Linq.Table<view_test> view_tests
		{
			get
			{
				return this.GetTable<view_test>();
			}
		}
		
		public System.Data.Linq.Table<view_trn_station> view_trn_stations
		{
			get
			{
				return this.GetTable<view_trn_station>();
			}
		}
		
		public System.Data.Linq.Table<view_trn_station_inhour> view_trn_station_inhours
		{
			get
			{
				return this.GetTable<view_trn_station_inhour>();
			}
		}
		
		public System.Data.Linq.Table<view_trn_station_report> view_trn_station_reports
		{
			get
			{
				return this.GetTable<view_trn_station_report>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_trn_station_insert")]
		public int sp_trn_station_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> station_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), station_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.master_station")]
	public partial class master_station : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _station_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstation_nameChanging(string value);
    partial void Onstation_nameChanged();
    #endregion
		
		public master_station()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_name", DbType="NVarChar(50)")]
		public string station_name
		{
			get
			{
				return this._station_name;
			}
			set
			{
				if ((this._station_name != value))
				{
					this.Onstation_nameChanging(value);
					this.SendPropertyChanging();
					this._station_name = value;
					this.SendPropertyChanged("station_name");
					this.Onstation_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trn_station")]
	public partial class trn_station : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _station_id;
		
		private System.Nullable<System.DateTime> _time_stamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstation_idChanging(System.Nullable<int> value);
    partial void Onstation_idChanged();
    partial void Ontime_stampChanging(System.Nullable<System.DateTime> value);
    partial void Ontime_stampChanged();
    #endregion
		
		public trn_station()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_id", DbType="Int")]
		public System.Nullable<int> station_id
		{
			get
			{
				return this._station_id;
			}
			set
			{
				if ((this._station_id != value))
				{
					this.Onstation_idChanging(value);
					this.SendPropertyChanging();
					this._station_id = value;
					this.SendPropertyChanged("station_id");
					this.Onstation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this.Ontime_stampChanging(value);
					this.SendPropertyChanging();
					this._time_stamp = value;
					this.SendPropertyChanged("time_stamp");
					this.Ontime_stampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_test")]
	public partial class view_test
	{
		
		private string _station_name;
		
		private System.Nullable<int> @__1;
		
		private System.Nullable<int> @__2;
		
		private int @__3;
		
		private int @__4;
		
		private int @__5;
		
		public view_test()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_name", DbType="NVarChar(50)")]
		public string station_name
		{
			get
			{
				return this._station_name;
			}
			set
			{
				if ((this._station_name != value))
				{
					this._station_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Int")]
		public System.Nullable<int> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Int")]
		public System.Nullable<int> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Int NOT NULL")]
		public int _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4]", Storage="__4", DbType="Int NOT NULL")]
		public int _4
		{
			get
			{
				return this.@__4;
			}
			set
			{
				if ((this.@__4 != value))
				{
					this.@__4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5]", Storage="__5", DbType="Int NOT NULL")]
		public int _5
		{
			get
			{
				return this.@__5;
			}
			set
			{
				if ((this.@__5 != value))
				{
					this.@__5 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_trn_station")]
	public partial class view_trn_station
	{
		
		private System.Nullable<int> _station_id;
		
		private System.Nullable<System.DateTime> _TimeStampHour;
		
		private System.Nullable<int> _count;
		
		private string _station_name;
		
		public view_trn_station()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_id", DbType="Int")]
		public System.Nullable<int> station_id
		{
			get
			{
				return this._station_id;
			}
			set
			{
				if ((this._station_id != value))
				{
					this._station_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStampHour", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeStampHour
		{
			get
			{
				return this._TimeStampHour;
			}
			set
			{
				if ((this._TimeStampHour != value))
				{
					this._TimeStampHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_name", DbType="NVarChar(50)")]
		public string station_name
		{
			get
			{
				return this._station_name;
			}
			set
			{
				if ((this._station_name != value))
				{
					this._station_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_trn_station_inhours")]
	public partial class view_trn_station_inhour
	{
		
		private System.Nullable<int> _station_id;
		
		private System.Nullable<System.DateTime> _TimeStampHour;
		
		private System.Nullable<int> _count;
		
		private string _station_name;
		
		private System.Nullable<long> _in_hours;
		
		public view_trn_station_inhour()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_id", DbType="Int")]
		public System.Nullable<int> station_id
		{
			get
			{
				return this._station_id;
			}
			set
			{
				if ((this._station_id != value))
				{
					this._station_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStampHour", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeStampHour
		{
			get
			{
				return this._TimeStampHour;
			}
			set
			{
				if ((this._TimeStampHour != value))
				{
					this._TimeStampHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_name", DbType="NVarChar(50)")]
		public string station_name
		{
			get
			{
				return this._station_name;
			}
			set
			{
				if ((this._station_name != value))
				{
					this._station_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_hours", DbType="BigInt")]
		public System.Nullable<long> in_hours
		{
			get
			{
				return this._in_hours;
			}
			set
			{
				if ((this._in_hours != value))
				{
					this._in_hours = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_trn_station_report")]
	public partial class view_trn_station_report
	{
		
		private System.Nullable<int> _station_id;
		
		private string _station_name;
		
		private System.Nullable<System.DateTime> _time_stamp;
		
		private System.Nullable<int> _avg;
		
		private System.Nullable<int> _min;
		
		private System.Nullable<int> _max;
		
		public view_trn_station_report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_id", DbType="Int")]
		public System.Nullable<int> station_id
		{
			get
			{
				return this._station_id;
			}
			set
			{
				if ((this._station_id != value))
				{
					this._station_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_name", DbType="NVarChar(50)")]
		public string station_name
		{
			get
			{
				return this._station_name;
			}
			set
			{
				if ((this._station_name != value))
				{
					this._station_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", DbType="Date")]
		public System.Nullable<System.DateTime> time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this._time_stamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avg", DbType="Int")]
		public System.Nullable<int> avg
		{
			get
			{
				return this._avg;
			}
			set
			{
				if ((this._avg != value))
				{
					this._avg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_min", DbType="Int")]
		public System.Nullable<int> min
		{
			get
			{
				return this._min;
			}
			set
			{
				if ((this._min != value))
				{
					this._min = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max", DbType="Int")]
		public System.Nullable<int> max
		{
			get
			{
				return this._max;
			}
			set
			{
				if ((this._max != value))
				{
					this._max = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
